version: "3.1"
services:
  nginx:
    image: <name of image present in own registry of gitlab >nginx:latest
    container_name: bss-auth-nginx
    ports:
      - "9080:80"
      - "9443:443"
    expose:
      - "9000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app

  app:
    image: node:8
    container_name: testing-app
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mongodb
    ports:
      - "9000"
    entrypoint: /application/start_application.sh
    environment:
      "NODE_ENV": "development"

  mongodb:
    image: mongo:latest
    container_name: testing
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

