version: "3.1"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=tododb-dev
      - MONGO_INITDB_ROOT-USERNAME=test
      - MONGO_INITDB_ROOT-PASSWORD=test
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    ports:
      - "27017:27017"
